### ISSUE TITLE
bug: eza hangs with option `--git` in home directory

### ISSUE THREAD

**Issue by shynst** [eza-community/eza#1049]
I have a git repository in my home directory to sync my dot-files and configurations across my Macs.
Running `eza -l --git` seems to hang, or take a really long long time. 
The process `fileproviderd` is at nearly 100% CPU. I gave up after 10 minutes.

- version of eza: `v0.18.18 [+git]`
- command-line arguments: `eza -l --git`
- shell and terminal: tested on kitty as well as on macOS build-in Terminal
- operating system / hardware: macOS Sonoma 14.5 / Mac mini M1

**Comment by shynst** [comment]
Update: it does finish after 20 mins or so. Producing this result:

```
stefan@applecrumb:~ % eza -l --git
drwx------@ - stefan 18 Mar 11:09 -N Applications
drwxr-xr-x@ - stefan  5 Apr  2023 -- Cryptomator
drwx------@ - stefan 26 Jun 12:43 -N Desktop
drwx------  - stefan  3 Apr  2023 -N Documents
drwx------@ - stefan  1 Jul 14:51 -N Downloads
drwx------  - stefan  3 Apr 11:15 -N Library
drwxr-xr-x@ - stefan  4 Oct  2023 -N Libs
drwx------  - stefan 27 Nov  2023 -N Movies
drwx------  - stefan 14 Sep  2022 -N Music
drwx------  - stefan 16 Mar  2022 -- Parallels
drwx------  - stefan 16 Mar  2022 -N Pictures
drwxr-xr-x@ - stefan 19 Apr  2023 -N Projects
drwxr-xr-x  - stefan 16 Mar  2022 -N Public
```

Why does it take so long??

**Comment by PThorpe92** [comment]
Wow, that is a long time. :eyes: 

When I run eza in my `Projects` directory that contains approximately 50+ git repos, with the `--git-repos` & `--git` flags, it takes about 1 second to generate the output.

Is this directory mounted from some kind of vfs? or is there anything unique about it? 

What is the output like when you run eza in other directories containing git repositories?

**Comment by shynst** [comment]
There is nothing special about my file system. The only thing which is unusual maybe, is that I have a git-repo in my home directory at `/Users/stefan`.

Afaik these are the directories affected by the dead-slow-bug:

- my home directory
- all subfolders of home (recursive) that do not have their own git-repo

I solved it for now by ignoring all directories and its'content (`/*/*` in `.gitignore`) and by adding just the ones I'd like to track (`!/.config/**`)

**Comment by MrAureliusR** [comment]
Having a git repo in your home directory is a bad idea, as it will make every subfolder also part of that repo and therefore take ages to parse. If you want to track your dotfiles, create a folder in your home directory called dotfiles and hardlink all your dotfiles there. Then create a git repo in that folder, and voila!
Make sure you create hardlinks and not symlinks. Hardlinks are different in that they literally appear as the file itself -- it points to the same inode as the file it's linked to. Symlinks are different and are more like a shortcut or pointer at a higher level, and I believe git adds these *as* symlinks instead of the files they are pointed to.

I know this doesn't solve the bug for eza but I think this is mostly unsolvable because of the huge number of files needed to be parsed when the entire home directory/partition is one gigantic git repo. Also, this will cause issues with shell themes that show info about git repos. It will show that you are always in a git repo, because technically you _are_ always in a git repo whenever you are anywhere in your home directory tree.

**Comment by cafkafk** [comment]
> At least I'm assuming under the hood eza is using git to do the parsing?

Specifically [libgit2](https://libgit2.org/)

**Comment by shynst** [comment]
> Having a git repo in your home directory is a bad idea, as it will make every subfolder also part of that repo and therefore take ages to parse.

I agree!

>If you want to track your dotfiles, create a folder in your home directory called dotfiles and hardlink all your dotfiles there. Then create a git repo in that folder, and voila! Make sure you create hardlinks and not symlinks. Hardlinks are different in that they literally appear as the file itself -- it points to the same inode as the file it's linked to. Symlinks are different and are more like a shortcut or pointer at a higher level, and I believe git adds these _as_ symlinks instead of the files they are pointed to.
> 
This is also a valid proposal, but I stick with the solution I came up with.

Considering, this issue is most likely git-related and is easy to solve, I am closing this issue.
