### ISSUE TITLE
aarch64-linux not supported on Nix

### ISSUE THREAD

**Issue by joliss** [eza-community/eza#1254]
eza compiles fine on my AArch64 Linux (`cargo build --release && ./target/release/eza`), but if I try to run it via Nix, it doesn't seem to work:

```
$ nix run github:eza-community/eza
error: cannot find flake attribute 'github:eza-community/eza#defaultApp.aarch64-linux'
```

I'm running Nix 2.6.0 on Ubuntu 22.04.

**Comment by cafkafk** [comment]
> Nix 2.6.0

I'm pretty sure the problem here is nix 2.6 is pretty old. The output attribute `defaultApp` is long gone, but we do expose a `packages.arch64-linux.default`, which never versions should default to now.

`nix run 'github:eza-community/eza#packages.arch64-linux.default` should work I assume, does it work for you?

**Comment by joliss** [comment]
Ah, I upgraded to Ubuntu 24.04 today, which ships Nix 2.18.1, and it works with the newer Nix!

(It turns out to have a slower startup time when run via Nix -- 0.1 seconds -- so I'm happily running it after installing with `cargo install` now.)
