### ISSUE TITLE
Add `eza` to Scoop

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#299]
On another note, [`eza`](https://github.com/ScoopInstaller/Main/blob/master/bucket/eza.json) has been added to Scoop. Might as well add that to the readme.

_Originally posted by @sitiom in https://github.com/eza-community/eza/issues/298#issuecomment-1717764374_

**Comment by sitiom** [comment]
It seems like Scoop hasn't picked up the new version since the format of the binaries has changed in the latest release (zipped in https://github.com/eza-community/eza/releases/tag/v0.11.1), opening up a PR for it: https://github.com/ScoopInstaller/Main/pull/5102

Note that usually Scoop already auto-updates the manifest from their bucket and nothing has to be done upstream, except for cases like these where the URL has changed and it breaks the [`autoupdate`](https://github.com/ScoopInstaller/Main/blob/2bb53493132b7620da730c7e1060580d9139c039/bucket/eza.json#L20-L26) field.
