### ISSUE TITLE
feat:  provide package prebuilt with musl, rather than glibc

### ISSUE THREAD

**Issue by yangyingchao** [eza-community/eza#329]
It appears that eza is currently linked with glibc, which can cause compatibility issues when running with an old version of glibc. However, if eza is built with static musl instead of libc, it can be executed on older operating systems regardless of the libc version.

As an example of this approach in action, you can take a look at diskus, which has already been implemented in this way. You can find the GitHub action for diskus at https://github.com/sharkdp/diskus/blob/master/.github/workflows/CICD.yml.

In my experience, I have compiled exa with docker using https://hub.docker.com/r/ekidd/rust-musl-builder/. It would be great if a prebuilt version of eza could be linked with musl directly to simplify the process even further.

**Comment by cafkafk** [comment]
> The usage of a docker container seems a bit complicated for just compiling to me.

I mean technically, we right now use a docker container through cross-r, and likely we'd prefer solutions to also be made this way. The details can be found in the justfile

**Comment by yangyingchao** [comment]
I am not familiar with your compiling process, but if you use GitHub Actions, consider using the Rust static build action from the GitHub Marketplace. It can be found at https://github.com/marketplace/actions/rust-static-build and may be useful for your purposes.

**Comment by gierens** [comment]
> The usage of a docker container seems a bit complicated for just compiling to me.

Cross compiling without docker through cross in out case is actually more complicated, you need the corresponding compiler installed on you system and have to tell rust where to find it, need corresponding glibc versions, the story goes on ... That's why we use cross which takes care of all that inside a container, so you don't have to mess with you system packages, because installing multiple glibc versions isn't funny either.

> However, if eza is built with static musl instead of libc, it can be executed on older operating systems regardless of the libc version.

I don't think we should replace those, maybe we can add such builds additionally ... @cafkafk I just checked, was able to compile with `cross build --release --target=x86_64-unknown-linux-musl`.

**Comment by cafkafk** [comment]
> @cafkafk I just checked, was able to compile with `cross build --release --target=x86_64-unknown-linux-musl`.

I'll send a pr, then I can also try and fix checksums
