### ISSUE TITLE
bug: different behaviour from `ls` when stdout is not a tty.

### ISSUE THREAD

**Issue by slqy123** [eza-community/eza#441]
When I am using `eza` with `xargs -I`, I get different output with `ls`.
```fish
❯ ls
1  2  3

❯ /bin/ls | xargs -I {} echo {} {}
1 1
2 2
3 3

❯ /bin/eza | xargs -I {} echo {} {}
1  2  3 1  2  3
```

It seems that when stdout is not a tty, `ls` will separate each file by `'\n'`
```fish
❯ /bin/ls > ../ls_out
❯ /bin/eza > ../eza_out
❯ diff eza_out ls_out
1c1,3
< 1  2  3
---
> 1
> 2
> 3

❯ /bin/ls > /dev/pts/2
❯ 1  2  3
```

env:
- findutils 4.9.0-3
- coreutils 9.3-1
- eza 0.13.1-1

**Comment by cafkafk** [comment]
> When I am using eza with xargs -I, I get different output with ls.

```
❯ eza
1  2  3

~/stu 
✦ ❯ ls | xargs -I {} echo {} {}
1 1
2 2
3 3

~/stu 
✦ ❯ eza | xargs -I {} echo {} {}
1 1
2 2
3 3
```

I can't reproduce this. Can you try running with #438?

**Comment by slqy123** [comment]
> I can't reproduce this. Can you try running with #438?

This dose not work too.
```
eza/target/release on  main
❯ ./eza | xargs -I {} echo {} {}
build  deps  examples  eza  eza.d  incremental  libeza.d  libeza.rlib build  deps  examples  eza  eza.d  incremental  libeza.d  libeza.rlib
```

**Comment by MartinFillon** [comment]
Cannot reproduce too

**Comment by hehelego** [comment]
I can reproduce this exactly.

```
> /bin/eza | xargs -I {} echo {} {}
Desktop  Documents  Downloads  go  MOOC  Music  Pictures  Public  QAQ  SHTU  SOUND  Templates  Videos Desktop  Documents  Downloads  go  MOOC  Music  Pictures  Public  QAQ  SHTU  SOUND  Templates  Videos

> /bin/ls | xargs -I {} echo {} {}
Desktop Desktop
Documents Documents
Downloads Downloads
go go
MOOC MOOC
Music Music
Pictures Pictures
Public Public
QAQ QAQ
SHTU SHTU
SOUND SOUND
Templates Templates
Videos Videos
```

**Comment by hehelego** [comment]
Also, the last release of `exa` behaves like ls. You can get it here: https://github.com/ogham/exa/releases/tag/v0.10.1

**Comment by hehelego** [comment]
#438 only dealt with `--color=auto` without touching code handling grid/oneline output. That patch should not have any effect.  But I think finding and replacing `terminal_size::terminal_size()` calls with `std::io::stdout().is_terminal()` can fix this.


BTW, I can expect much more `ls` compatbility issues like this one to come out, as `eza` gains popularity.
I kind of know what are people's feeling. I've been using `exa` as a drop-in replacement of `ls` for nearly two years and it was mostly fine. I switched to `eza` from `exa` roughly a 2/3 weeks ago when a `pacman -Syu` update replaced `exa` wiith `eza` automatically (now if you try to install with `pacman -S exa`, what you'll actaully get is our `eza`). That migration did not go smoothly. I noticed `eza` behavior differs from `exa`, causing some small trouble, because I actually have `alias ls=exa` in my `config.fiish`.  
You are (I mean, I am) really expecting `eza` to be `ls` compatible especially when it comes as a replacement of `exa` which was `ls` compatible.

**Comment by hehelego** [comment]
I think I can fix that. See https://github.com/eza-community/eza/pull/438#issuecomment-1741188125
I've tried to replace it with `terminal_size_with_raw_fd()` on `stdout` and it works

**Comment by hehelego** [comment]
> > You are (I mean, I am) really expecting `eza` to be `ls` compatible especially when it comes as a replacement of `exa` which was `ls` compatible.
> 
> Well we're always looking for people willing to help that effort. We've been discussing adding a flag that would ideally be strictly compatible with `ls`, and we've worked a lot on getting proper integration testing to ensure issues like these don't happen suddenly.

We will have more people. 
`eza` has 2.6k stars. There are certainly people who are willing to help.

**Comment by hehelego** [comment]
@slqy123 can you try to run with https://github.com/eza-community/eza/pull/438 now?  
It should have fixed the problem. ~~at least on my machine~~.

**Comment by slqy123** [comment]
> @slqy123 can you try to run with #438 now? It should have fixed the problem. ~at least on my machine~.

Yes, it works pretty well now, thanks for your help.
