### ISSUE TITLE
"tree" is ~4x times faster than "eza --tree"

### ISSUE THREAD

**Issue by FedericoMuciaccia** [eza-community/eza#830]
I've noticed that the original `tree` command is ~4x times faster than the `eza --tree` command (at least on my laptop), despite producing the same output.

This is not strictly a bug, but it's a clue that perhaps some important optimizations may be still missing in the `eza` codebase.

We all want our Rust alternatives to be the fastest in town :)

**Comment by JustLinuxUser** [comment]
For me 
`eza --tree`is  11.41s
`tree  1.08s` + ~1s of terminal rendering (which is slower for tree)
One observable difference, the tree command doesn't stop before printing,
which leads me to belive, it doesn't build an internal map of the structure of files and folders, I think it prints as it crawls, and it is good at it's job. I think eza takes time to do allocations and remembering what is where before printing, which makes it slower, because it's not just a tree printer, and it reuses (probably) the same code for other file tree things

**Comment by luketych** [comment]
Yes it is very very slow to the point of being unusable.

**Comment by cafkafk** [comment]
> Please fix, it's not that difficult.

Famous last words. If you're so confident, why don't you open a PR optimizing the tree command then, after all, it's not that difficult?

**Comment by luketych** [comment]
I already did it for my personal use. As you may or may not know opening a
pr opens up a whole other can of worms and leads to neverending
responsibility.

Or maybe you have never done so before.

**Comment by cafkafk** [comment]
As interesting as it is to improve eza performance, nothing here is actually an actionable issue, so there isn't anything here "to be done". I think this kind of issue is more appropriate as a discussion topic.
