### ISSUE TITLE
Few eza icons different compared to exa icons

### ISSUE THREAD

**Issue by mohanrajpExploring** [eza-community/eza#998]
**[ Issue ]**

Few eza icons seem to look invalid compared to exa icons.

Please have a look at the below screenshot: **Left: exa & right: eza**

![image](https://github.com/eza-community/eza/assets/168116222/12c6a85e-4e81-4666-86df-bcf76ae93996)

Here have look at the file named `.bash_history`, `.bash_logout`, `.bashrc` & `.profile` on the right which are output\
from eza using the command `alias ls='eza -lagh --time-style=long-iso --group-directories-first --icons'` they\
are all displayed with icon `#!` which seem invalid as compared to left output using exa.

Is this expected outcome using eza ?

---

Thanks,
Please let me know if further information is required.

**Comment by gierens** [comment]
Yes, this is intentional ... we refactored around a lot in the icons module and in the process also added and changed icons based on user requests and also our own judgement. Whether we improved things is obviously partly subjective and a matter of taste, but that is one reason we are currently working on a config file feature that would also allow users to override icons, see #840
